#!/bin/bash

IP=$(hostname -f)
count=0

curl -A kueued-dbupdate --silent http://${IP}:8080/updateDB/full &> /dev/null

(while ( true ); do

    count=$(($count+1))

    if [ "$count" -lt "250" ]; then

        RESULT=$(curl -A kueued-dbupdate --silent http://${IP}:8080/updateDB | tail -1)

    else

        RESULT=$(curl -A kueued-dbupdate --silent http://${IP}:8080/updateDB/full | tail -1)
        count=0

    fi

    echo $(date) > /var/log/kueued/lastdbupdate

    if [ "$RESULT" == "UPDATE FINISHED" ]; then

            echo "$(date +%F\ %X) - Update successful :)"

    else
            echo "$(date +%F\ %X) - Something went wrong - please check server logs :("

    fi

    sleep 5

done) >> /var/log/kueued/dbupdate.log

